### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by alldataback-com** [lukstep/raspberry-pi-pico-docker-sdk#5]
Thanks for your great ideas. How did you debug in docker env? Would you like to make a tutorial? Thanks!

**Comment by lukstep** [comment]
I'm currently working on a Mac and I use "UART printing" for debugging.  Using Pico Probe as a debugger could be difficult on Windows or Mac as a Docker host. The problem with Pico Probe is that it's hard to get from the container to the COM ports

**Comment by alldataback-com** [comment]
i think we can use GDB remote debug.

**Comment by lukstep** [comment]
I have an idea how this could be done, when I test it I will let you know.

**Comment by lukstep** [comment]
I've made tutorial how to debug using Debug Probe and OpenOCD.
https://github.com/lukstep/raspberry-pi-pico-docker-sdk?tab=readme-ov-file#pico-memory-flashing-and-debugging-via-pico-probe-and-openocd
